#!/usr/bin/env python3

import os
import errno
import subprocess
import signal
import sys

FIFO = '/tmp/statusbar_volume'

if not os.path.exists(FIFO):
  os.mkfifo(FIFO)

print("vol {}%".format(subprocess.run(['get-volume'], capture_output=True).stdout.decode().rstrip()), end='', flush=True)
while True:
  with open(FIFO) as pipe: print("vol {}%".format(pipe.read().rstrip()), end='', flush=True)
