#!/usr/bin/env python3

import os
import errno
import subprocess

FIFO = '/tmp/statusbar_volume'

try:
  if os.path.isfile(FIFO):
    os.remove(FIFO)

  try:
    os.mkfifo(FIFO)
  except OSError as oe:
    if oe.errno != errno.EEXIST:
      raise

  print("vol {}%".format(subprocess.run(['get-volume'], capture_output=True).stdout.decode().rstrip()), end='', flush=True)

  while True:
    with open(FIFO) as pipe:
      data = pipe.read().rstrip()
      print("vol {}%".format(data), end='', flush=True)

except KeyboardInterrupt:
  pass

os.remove(FIFO)
