#!/usr/bin/env python3

import i3ipc
import sys

i3 = i3ipc.Connection()

def print_workspaces():
    output = ""
    for workspace in i3.get_workspaces():
        if workspace['focused']:
            output += '<span bgcolor="#000000FF"> ' + str(workspace['num']) + ' </span>'
        else:
            output += " " + str(workspace['num']) + " "
    print(output)
    sys.stdout.flush()	

def on_workspace_focus(self, e):
    print_workspaces()

print_workspaces()
i3.on('workspace', on_workspace_focus)
i3.main()
