#!/bin/bash

if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit
fi

export USER=root
export SUDO_USER=schutz
export SUDO_UID=1000
export SUDO_GID=1000

retries_until=0
retries_while=0

STATUSBAR_VPN_FIFO=/tmp/statusbar_vpn

until [[ ! -z $(nmap -sn protonvpn.com 2>/dev/null | grep 'Host is up') ]]; do
  ((retries_until++))
  if [[ $retries_until -le 5 ]]; then
    sleep 5
  else
    sleep 20
  fi
done

if [[ -p $STATUSBAR_VPN_FIFO ]]; then
  sudo -u $(stat -c %U $STATUSBAR_VPN_FIFO) bash -c "exec 3<>$STATUSBAR_VPN_FIFO; echo -n ↺ >$STATUSBAR_VPN_FIFO"
fi

result=$(protonvpn c -r | grep Connected)

if [[ -p $STATUSBAR_VPN_FIFO ]]; then
  if [[ -z "$result"  ]]; then
    sudo -u $(stat -c %U $STATUSBAR_VPN_FIFO) bash -c "exec 3<>$STATUSBAR_VPN_FIFO; echo -n Off >$STATUSBAR_VPN_FIFO"
  else
    sudo -u $(stat -c %U $STATUSBAR_VPN_FIFO) bash -c "exec 3<>$STATUSBAR_VPN_FIFO; echo -n On >$STATUSBAR_VPN_FIFO"
  fi
fi

while [[ ! -z $(nmap -sn protonvpn.com 2>/dev/null | grep 'Host is up') ]]; do
  ((retries_while++))
  if [[ $retries_while -le 5 ]]; then
    sleep 5
  else
    sleep 20
  fi
done

if [[ -p $STATUSBAR_VPN_FIFO ]]; then
  sudo -u $(stat -c %U $STATUSBAR_VPN_FIFO) bash -c "exec 3<>$STATUSBAR_VPN_FIFO; echo -n Off >$STATUSBAR_VPN_FIFO"
fi
