#!/bin/bash

if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit
fi

export USER=root
export SUDO_USER=schutz
export SUDO_UID=1000
export SUDO_GID=1000

STATUSBAR_VPN_FIFO=/tmp/statusbar_vpn

if [[ -p $STATUSBAR_VPN_FIFO ]]; then
  sudo -u $(stat -c %U $STATUSBAR_VPN_FIFO) bash -c "exec 3<>$STATUSBAR_VPN_FIFO; echo -n ↺ >$STATUSBAR_VPN_FIFO"
fi

protonvpn d

if [[ -p $STATUSBAR_VPN_FIFO ]]; then
  sudo -u $(stat -c %U $STATUSBAR_VPN_FIFO) bash -c "exec 3<>$STATUSBAR_VPN_FIFO; echo -n Off >$STATUSBAR_VPN_FIFO"
fi
